trigger: none
pr: none

schedules:
  - cron: "*/2 * * * *"
    displayName: "Run every 2 minutes"
    always: true
    branches:
      include:
        - main

jobs:
- job: DummyServerJob
  displayName: "Dummy schedule test"
  pool: server
  steps: []
