trigger: none
pr: none

schedules:
  - cron: "*/2 * * * *"  # Runs every day at midnight UTC
    displayName: Daily Dummy Run
    always: true
    branches:
      include:
        - main

jobs:
- job: DummyServerJob
  displayName: "Run without Agent"
  pool: selfHosted
  steps:
    - task: Delay@1
      displayName: "Simulate job with Delay"
      inputs:
        delayForSeconds: 5
